# -*- coding: utf-8 -*-
"""LoanGuard: Basic Decision Tree Classifier

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xDlS2tAMNlgzIRnhO0_WbWZyzLAMm_wb

# *LoanGuard: Basic Decision Tree Classifier*

# 🤓 Situação:

Uma empresa de empréstimo de automóveis está passando por uma situação muito complicada. Ela está com uma alta demanda para uma frota reduzida e uma alta taxa de clientes inadimplentes, ou seja, clientes que não pagam o empréstimo no tempo devido.

- Alta demanda
- Frota reduzida
- Inadimplência

Isso está gerando um grande prejuízo para a empresa. E nós fomos contratados para ajudar a melhorar essa situação da empresa, para identificar esses clientes inadimplentes antes mesmo da empresa conceder o empréstimo do veículo.

Para resolver essa situação, essa empresa nos forneceu uma base de dados em formato CSV com dados históricos de clientes inadimplentes. Vamos utilizar essa base de dados para construir um modelo de inteligência artificial que vai conseguir classificar os clientes entre adimplentes e inadimplentes.

# 🎯 Objetivo:

Criar um modelo de classificação em Machine Learning que permita identificar clientes inadimplentes em uma empresa de empréstimo de automóveis evitando prejuizos.

# 🏃‍♂️ Pipeline:

1. Leitura da base de dados que iremos usar:
link: https://cdn3.gnarususercontent.com.br/3069-classificacao/emp_automovel.csv

2. Criação do modelo de classificação que mais se adequa ao nosso caso

3. Validação de modelos
  - Usaremos treino, validação e teste
  - Usaremos Cross Validation (Validação cruzada)

# 🚀 Mão na massa:

### 1. Importando bibliotecas e lendo o arquivo necessário:
"""

import pandas as pd

dados = pd.read_csv('/content/emp_automovel.csv')

dados.head()

"""Nossa ultima coluna "inadimplente" que já está em formato numérico é o que queremos identificar (variável alvo). Repare que a base de dados já está inteiramente tratada e toda numérica, sem ser necessário usar o one_hot_enconder."""

# Separando variável alvo das explicativas:

y = dados['inadimplente']
y

x = dados.drop('inadimplente', axis = 1)
x

"""Agora que as duas já estão separadas, podemos seguir com o nosso processo de criação de modelos.

### 2. Divisão de treino e teste e validação do nosso grupo

Para validar os nossos dados vamos separar em 3 partes: Treino, teste e validação! Isso funciona para que tenhamos uma maior confiança em relação aos nossos dados.
"""

from sklearn.model_selection import train_test_split

# Vamos ter que dividir 2 vezes para ter os 3 conjuntos:

x, x_teste, y, y_teste = train_test_split(x, y, test_size = 0.15, stratify = y, random_state = 5)
x_treino, x_val, y_treino, y_val = train_test_split(x, y, stratify = y, random_state = 5)

"""### 3. Criação do algortimo: Decision Thee"""

from sklearn.tree import DecisionTreeClassifier

model = DecisionTreeClassifier()
model.fit(x_treino,y_treino)

print(f'Acurácia de treino: {model.score(x_treino, y_treino)*100} %')
print(f'Acurácia de validação: {model.score(x_val, y_val)*100} %')

"""Vemos que o desempenho está caindo muito drasticamente, o que pode indicar que o nosso modelo está decorando o padrão do teste, o que torna ele inapto para outros conjuntos, para mudar isso, vamos usar o max_depth."""

modelo = DecisionTreeClassifier(max_depth = 10)
modelo.fit(x_treino, y_treino)

print(f'Acurácia de treino: {modelo.score(x_treino, y_treino)}')
print(f'Acurácia de validação: {modelo.score(x_val, y_val)}')

# Gerando um gráfico com as decisões:

from sklearn.tree import plot_tree
import matplotlib.pyplot as plt

plt.figure(figsize = (20,20))
plot_tree(model, filled = True, class_names = ['não', 'sim'], fontsize = 1, feature_names = dados.columns);

"""### 4. Acurácia, precisão e recall

Com isso, embora a acurrâcia do treino tenha caido, a da validação aumentou significativamente. No entanto, a acurâcia nos trás apenas um valor geral, precisamos avaliar especificamente cada uma das classes. Para isso, vamos usar o que chamamos de matriz de confusão:
"""

from sklearn.metrics import confusion_matrix

y_previsto = modelo.predict(x_val)
matriz_confusao = confusion_matrix(y_val, y_previsto)
print(matriz_confusao)

"""Vamos melhorar um pouco o aspecto visual desse resultado, pois não da para entender muito no momento"""

from sklearn.metrics import ConfusionMatrixDisplay

viz = ConfusionMatrixDisplay(confusion_matrix = matriz_confusao)
viz.plot();

"""Na coluna temos os valores reais, e na linha os valores previstos. Essa matriz de confusão revela que, embora o modelo tenha um bom desempenho ao identificar clientes adimplentes (com apenas 116 falsos positivos), ele tem uma baixa capacidade de identificar clientes inadimplentes, já que 960 casos foram classificados incorretamente. Isso indica que o modelo está subestimando a quantidade de clientes que não pagariam o empréstimo, o que poderia representar um risco significativo para a empresa, uma vez que esses clientes podem não ser identificados a tempo de prevenir perdas financeiras.

- True Positives (TP): O modelo identificou corretamente 42 casos de clientes inadimplentes (1) como inadimplentes.
- True Negatives (TN): O modelo identificou corretamente 10000 casos de clientes adimplentes (0) como adimplentes.
- False Positives (FP): O modelo incorretamente classificou 116 casos de clientes adimplentes (0) como inadimplentes.
- False Negatives (FN): O modelo incorretamente classificou 960 casos de clientes inadimplentes (1) como adimplentes.
"""

# Mudando o 0 e 1 para suas categorias para ficar mais fácil interpretar;

viz = ConfusionMatrixDisplay(confusion_matrix = matriz_confusao, display_labels = ['Adimplente', 'Inadimplente'])
viz.plot();

# Calculando Acurácia levando isso em conta

from sklearn.metrics import accuracy_score

print(f'Acurácia: {accuracy_score(y_val, y_previsto)*100} % ')

# Calculando recall e precisão:

from sklearn.metrics import precision_score, recall_score

print(f'Precisão: {precision_score(y_val, y_previsto)}')
print(f'Recall: {recall_score(y_val, y_previsto)} ')

"""Isso indica que o nosso modelo não está indo muito bem, com valores de precisão e recall muito próximos a zero - uma melhor métrica seria próxima de 1.

O que vemos como mais importante é o recall, pois ele pode levar a empresa a um prejuizo e isso é diretamente relacionado ao nosso problema de negócios, sendo ele mais relevante vamos levar ele em conta.

Além disso temos o F1 score como outra função, que nos daria um equilibrio entre essas duas métricas - Não perder clientes e não ter prejuízos.

###  4.1 f1_score
"""

from sklearn.metrics import f1_score

print(f'F1_score : {f1_score(y_val, y_previsto)}')

"""Esse também é um valor bem baixo, principalmente por conta das outras duas estarem baixas também!

### 4.2 Curva ROC

Sendo o recall a métrica mais importante, vamos construir gráficos a partir dele para entender melhor o nosso modelo, usando primeiramente a curva ROC para saber se o modelo está diferenciando bem uma métrica da outra:
"""

from sklearn.metrics import RocCurveDisplay

RocCurveDisplay.from_predictions(y_val, y_previsto, name = 'Árvore de Decisão');

"""A curva ROC (Receiver Operating Characteristic Curve) apresentada mostra o desempenho de um modelo de Árvore de Decisão para a classificação de clientes inadimplentes. A linha segue quase uma diagonal perfeita, indicando que o modelo tem pouca ou nenhuma capacidade de discriminação entre as classes positiva e negativa. O valor da AUC (Área Sob a Curva - Quanto mais próximo de 1 melhor) é de 0,52, muito próximo de 0,5, o que sugere que o modelo está classificando os resultados quase aleatoriamente, com desempenho equivalente ao de um classificador que faz suposições aleatórias. O ideial seria uma linha quase reta, próxima ao 0 do eixo x e o 1 do eixo y.

### 4.2 Curva de precisão x Recall
"""

from sklearn.metrics import PrecisionRecallDisplay

PrecisionRecallDisplay.from_predictions(y_val, y_previsto, name = 'Árvore de decisão');

"""A curva Precision-Recall exibida demonstra o desempenho de uma Árvore de Decisão no contexto de detecção de clientes inadimplentes. A curva apresenta uma queda acentuada na precisão logo no início, com uma precisão alta apenas para baixíssimos valores de recall. Conforme o recall aumenta, a precisão rapidamente cai para valores muito baixos, estabilizando-se próxima a zero. O valor de AP (Average Precision) é de 0,09 - Quanto mais próximo de 1 melhor, o que indica que o modelo tem um desempenho muito fraco na distinção entre classes, especialmente em manter a precisão enquanto tenta aumentar o recall. Isso sugere que o modelo não é eficaz em identificar corretamente os clientes inadimplentes sem gerar um grande número de falsos positivos.

### 4.3 Avaliando todas ao mesmo tempo

Existe uma forma de avaliarmos tudo ao mesmo tempo e já podermos tirar conclusões diretas.
"""

from sklearn.metrics import classification_report

print(classification_report(y_val, y_previsto))

"""Com isso vemos que claramente há um desequilibrio dos dados, tendo muito mais '0's.

O relatório de classificação indica que o modelo de Árvore de Decisão possui uma alta precisão geral (91%), mas falha significativamente na identificação de clientes inadimplentes. Embora o modelo consiga identificar corretamente 99% dos clientes que não são inadimplentes (classe 0) e tenha uma precisão de 92% para essa classe, ele apresenta um desempenho muito fraco para a classe 1 (inadimplentes), com uma precisão de apenas 27% e um recall extremamente baixo de 4%, resultando em um F1-score de apenas 0,07. Esses resultados sugerem que, apesar da alta acurácia geral, o modelo é ineficaz para a tarefa específica de detectar inadimplentes, provavelmente devido ao desequilíbrio de classes, onde a classe 0 domina, mascarando a verdadeira performance do modelo para a classe minoritária.

### 4.4 Usando o KFOLD para validação cruzada

Ao invez de dividir esses dados apenas em treino, validação e teste, vamos usar o KFOLD para criar esses grupos de forma aleatória e testar K vezes para adequar ao processo de forma aleatória, o que garante que nossos conjuntos sejam mais homogêneos.
"""

from sklearn.model_selection import cross_validate, KFold

modelo = DecisionTreeClassifier(max_depth = 10)
kf = KFold(n_splits = 5, shuffle = True, random_state = 5)
cv_resultados = cross_validate(modelo, x, y, cv = kf)
cv_resultados

# Pegando os valores isolados de resultados do test score:

cv_resultados['test_score']

# Calculando algumas métricas em cima desses valores:

media = cv_resultados['test_score'].mean()
desvio_padrao = cv_resultados['test_score'].std()
print(f'Intervalo de confiança de: [{media - 2*desvio_padrao}, {media + 2* desvio_padrao}]') #Minimo e máximo são a média + ou - 2x o desvio padrão.

"""Vemos que nosso intervalo de confiança apresenta um desempenho entre 89 e 91% de acurácia, no entanto, o que queremos é o recall.

### 4.5 Validação cruzada com recall
"""

def intervalo_conf(resultados):
  media = resultados['test_score'].mean()
  desvio_padrao = resultados['test_score'].std()
  print(f'Intervalo de confiança de: [{media - 2*desvio_padrao} - {media + 2* desvio_padrao}]') #Minimo e máximo são a média + ou - 2x o desvio padrão.

# Usando o recall:

modelo = DecisionTreeClassifier(max_depth = 10)
kf = KFold(n_splits = 5, shuffle = True, random_state = 5)
cv_resultados = cross_validate(modelo, x, y, cv = kf, scoring = 'recall')
cv_resultados

intervalo_conf(cv_resultados)

"""Ainda estamos com valores baixos, mas isso, como vimos é por conta da desproporção de dados entre clientes adimplentes e inadimplentes. Vamos checar a proporção e identificar como separar se forma melhor no cross validate."""

dados['inadimplente'].value_counts(normalize = True)

"""91 % dos nossos dados são relacionados a clientes inadimplentes, ou seja, uma proporção significamente maior, e isso interfere muito no modelo. Portanto, precisamos estratificar melhor esses dados."""

from sklearn.model_selection import StratifiedKFold

modelo = DecisionTreeClassifier(max_depth = 10)
skf = StratifiedKFold(n_splits = 5, shuffle = True, random_state = 5)
cv_resultados = cross_validate(modelo, x, y, cv = skf, scoring = 'recall')

intervalo_conf(cv_resultados)

"""Vemos que nossa margem está muito melhor, mas o modelo ainda não está bom, como melhorar?

- Primeiro temos que lidar com a questão do Oversampling (Devido a falta de balanceamento dos dados), para isso, vamos tentar equilibrar esses dados.

### 4.6 Oversampling

O oversampling (sobreamostragem) normal, que seria o aleatório, duplica a quantidade de elementos da classe de menor quantidade de forma aleatória.

Porém, vamos utilizar um método conhecido como SMOTE (Synthetic Minority Over-sampling Technique ou técnica de sobreamostragem minoritária sintética). É um algoritmo que, ao invés de simplesmente duplicar os elementos da classe de menor quantidade, cria novos dados sintéticos com padrão semelhante aos dados que já existem.
"""

from imblearn.over_sampling import SMOTE

oversample = SMOTE()
x_balanceado, y_balanceado = oversample.fit_resample(x,y)

y_balanceado.value_counts(normalize = True)

"""Balanceou 50 - 50 %, vamos agora treinar o modelo novamente!"""

# Treinando o novo modelo:

modelo = DecisionTreeClassifier(max_depth = 10)
skf = StratifiedKFold(n_splits = 5, shuffle = True, random_state = 5)
cv_resultados = cross_validate(modelo, x_balanceado, y_balanceado, cv = skf, scoring = 'recall')

intervalo_conf(cv_resultados)

"""Vemos que o desempenho está muito melhor, mas avaliamos nos dados balanceados, e no mundo real não está assim, então temos que avaliar em conjuntos não balanceados. Para isso, vamos usar um pipeline de dados:

### 4.7 Pipeline dos dados

 Um pipeline é uma sequência de transformações, operações que realizamos nos dados.
"""

from imblearn.pipeline import Pipeline as imbpipeline

modelo = DecisionTreeClassifier(max_depth = 10)

pipeline = imbpipeline([('oversample', SMOTE()), ('arvore', modelo)])

skf = StratifiedKFold(n_splits = 5, shuffle = True, random_state = 5)
cv_resultados = cross_validate(pipeline, x, y, cv = skf, scoring = 'recall')

intervalo_conf(cv_resultados)

"""O nosso intervalo de confiança ja caiu bastante, mas o nosso processo está de fato mais correto e no seu uso indicado. É melhor que o nosso recall de antes, mas ainda é um valor baixo.

### 4.8 Undersampling (subamostragem)

Ao invés de aumentar a quantidade de dados da classe que tem menor quantidade, vamos fazer o contrário. Reduziremos a quantidade de dados da classe que tem maior quantidade, até que ela tenha a mesma quantidade de dados que a classe com a menor quantidade.

Existe um processo de undersampling aleatório que não utiliza nenhum critério para a remoção dos dados. Ele simplesmente remove dados aleatoriamente da base de dados da classe que tem maior quantidade. Porém, esse processo não é tão recomendado porque pode ser que, durante esse processo, dados importantes para o modelo compreender o padrão dos dados sejam perdidos.

Ao invés do undersampling aleatório, vamos aplicar outra técnica de undersampling que se chama NearMiss. Nessa estratégia, há um critério de escolher os elementos que vão continuar na base de dados que tenham um padrão bem parecido com os elementos que já existem na outra classe.
"""

from imblearn.under_sampling import NearMiss

modelo = DecisionTreeClassifier(max_depth = 10)
pipeline = imbpipeline([('undersample', NearMiss(version = 3)), ('arvore', modelo)])

skf = StratifiedKFold(n_splits = 5, shuffle = True, random_state = 5)
cv_resultados = cross_validate(pipeline, x, y, cv = skf, scoring = 'recall')

intervalo_conf(cv_resultados)

"""Usando essa estratégia, nosso resultado já melhorou de forma significativa, então vamos usar isso no nosso modelo final que vamos validar agora no nosso conjunto de teste!

## 5. Testando o nosso modelo:

Selecionamos o modelo que apresentou o melhor desempenho utilizando a estratégia de undersampling com o algoritmo NearMiss na versão 3. Este algoritmo irá balancear nossos dados e, a partir deles, vamos treinar o modelo com base nos dados para identificar o padrão de cada uma das classes.
"""

undersample = NearMiss(version = 3)
x_balanceado, y_balanceado = undersample.fit_resample(x, y)

modelo = DecisionTreeClassifier(max_depth = 10)
modelo.fit(x_balanceado, y_balanceado)
y_previsto = modelo.predict(x_teste)

print(classification_report(y_teste, y_previsto))
ConfusionMatrixDisplay.from_predictions(y_teste, y_previsto);

"""O relatório de classificação e a matriz de confusão indicam que o modelo está enfrentando dificuldades em distinguir corretamente entre as classes. Para a classe 0, a precisão é alta (94%), mas o recall é baixo (48%), significando que o modelo deixa de identificar muitos casos verdadeiros de classe 0. Já para a classe 1, a precisão é muito baixa (11%), embora o recall seja relativamente bom (70%), mostrando que o modelo identifica a maioria dos casos de classe 1, mas com muitos falsos positivos. A acurácia geral é de apenas 50%, refletindo o baixo desempenho do modelo. A matriz de confusão reforça esses problemas, mostrando um grande número de falsos positivos para a classe 0 e falsos negativos para a classe 1. Isso sugere que o modelo está enviesado e precisa de ajustes, como balanceamento de dados ou alteração do limiar de classificação, para melhorar sua performance geral."""

